 apiVersion: v1
 kind: Pod
 metadata:
   name: epic-mid-pod
   labels:
     app: epic-mid-pod
 spec:
   containers:
     - name: epic-mid-server
       image: mid-service:v1
       ports:
         - containerPort: 5002
     - name: epic-mid-mongo
       image: mongo
       ports:
         - containerPort: 27017