version: "3"
services:
  middleserver:
    build: ./
    ports:
    - "5000:5000"
    links: 
    - middlemongo
  middlemongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes: 
    - middleData:/data/middleDB

volumes:
  middleData:


